import { CodeEnum } from '../enums/code.enum';

export const keyboardLayoutConfig: { key: CodeEnum, classType?: string }[] = [
    { key: CodeEnum.Escape, classType: 'is-escape' },
    { key: CodeEnum.F1 },
    { key: CodeEnum.F2 },
    { key: CodeEnum.F3 },
    { key: CodeEnum.F4 },
    { key: CodeEnum.F5 },
    { key: CodeEnum.F6 },
    { key: CodeEnum.F7 },
    { key: CodeEnum.F8 },
    { key: CodeEnum.F9 },
    { key: CodeEnum.F10 },
    { key: CodeEnum.F11 },
    { key: CodeEnum.F12 },
    { key: CodeEnum.Backquote },
    { key: CodeEnum.Digit1 },
    { key: CodeEnum.Digit2 },
    { key: CodeEnum.Digit3 },
    { key: CodeEnum.Digit4 },
    { key: CodeEnum.Digit5 },
    { key: CodeEnum.Digit6 },
    { key: CodeEnum.Digit7 },
    { key: CodeEnum.Digit8 },
    { key: CodeEnum.Digit9 },
    { key: CodeEnum.Digit0 },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Backspace, classType: 'is-backspace' },
    { key: CodeEnum.Tab, classType: 'is-tab' },
    { key: CodeEnum.KeyQ },
    { key: CodeEnum.KeyW },
    { key: CodeEnum.KeyE },
    { key: CodeEnum.KeyR },
    { key: CodeEnum.KeyT },
    { key: CodeEnum.KeyZ },
    { key: CodeEnum.KeyU },
    { key: CodeEnum.KeyI },
    { key: CodeEnum.KeyO },
    { key: CodeEnum.KeyP },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Enter, classType: 'is-enter' },
    { key: CodeEnum.CapsLock, classType: 'is-capslock' },
    { key: CodeEnum.KeyA },
    { key: CodeEnum.KeyS },
    { key: CodeEnum.KeyD },
    { key: CodeEnum.KeyF },
    { key: CodeEnum.KeyG },
    { key: CodeEnum.KeyH },
    { key: CodeEnum.KeyJ },
    { key: CodeEnum.KeyK },
    { key: CodeEnum.KeyL },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.ShiftLeft, classType: 'is-shift-left' },
    { key: CodeEnum.IntlBackslash },
    { key: CodeEnum.KeyY },
    { key: CodeEnum.KeyX },
    { key: CodeEnum.KeyC },
    { key: CodeEnum.KeyV },
    { key: CodeEnum.KeyB },
    { key: CodeEnum.KeyN },
    { key: CodeEnum.KeyM },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.ShiftRight, classType: 'is-shift-right' },
    { key: CodeEnum.ControlLeft, classType: 'is-ctrl' },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.AltLeft, classType: 'is-alt' },
    { key: CodeEnum.Space, classType: 'is-space' },
    { key: CodeEnum.AltRight, classType: 'key is-alt' },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.Unidentified },
    { key: CodeEnum.ControlRight, classType: 'is-ctrl' },
];
